### ISSUE TITLE
No requirements.txt

### ISSUE THREAD

**Issue by signal-alesieur** [camunda/vault-dump-kv2#1]
Yo!
Just wanted to let you know that in the README you mention to run `pip3 install -r requirements.txt` to install dependencies.
You don't have a requirements.txt :-)
I understand the only one you need is `hvac`, so I'll you decide if you want to create a requirements file or just amend the instructions to do a `pip3 install hvac` :-)
Thanks!

**Comment by cmur2** [comment]
Thanks @signal-alesieur for bringing that problem up, I changed the project to use [pipenv](https://pipenv.pypa.io/) a while ago but forgot to update the README.

**Comment by cmur2** [comment]
In case you are not a fan of `pipenv` a look at the [Pipfile](https://github.com/camunda/vault-dump-kv2/blob/master/Pipfile#L8) also shows which dependency is needed :)
